spring.application.name=discovery-server

server.port=8761

# Le decimos a Eureka que no se registre a sí mismo ni busque a otros servidores
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false